services:
  - type: web
    name: auditdata-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: Recomendaciones_de_copiloto
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
